# Generated by Django 6.0.1 on 2026-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название монеты/волюты')),
                ('code', models.CharField(max_length=255, verbose_name='Название для api (BTC к примеру)')),
                ('image', models.FileField(upload_to='currency/', verbose_name='Фото или svg монеты/волюты')),
                ('background', models.CharField(max_length=255, verbose_name='Hex код для фона')),
                ('is_fiat', models.BooleanField(default=False, verbose_name='Фиатная валюта?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
