# Generated by Django 6.0.1 on 2026-01-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_walletaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер заявки')),
                ('amount_from', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Количество монет отправлено')),
                ('amount_to', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Количество монет получено')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('telegram', models.CharField(max_length=255, verbose_name='Телеграм')),
                ('wallet_to_receive', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк для получения')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Реквизиты')),
                ('status', models.CharField(choices=[('WAITING', 'Ожидание'), ('PROCESSING', 'В процессе'), ('DONE', 'Заказ выполнен'), ('EXPIRED', 'Просрочено'), ('CANCELED', 'Отклонено')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Срок жизни')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_currency', to='exchange.currency', verbose_name='Отдаёте')),
                ('selected_wallet_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.walletaddress', verbose_name='Адрес для отправки')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_currency', to='exchange.currency', verbose_name='Получаете')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
