# Generated by Django 6.0.1 on 2026-01-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название для api (BTC к примеру)'),
        ),
    ]
