# Generated by Django 6.0.1 on 2026-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок обработки после оплаты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='currency/', verbose_name='Фото или svg монеты/волюты'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR'),
        ),
    ]
