# Generated by Django 6.0.1 on 2026-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_order_processing_expires_at_alter_currency_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requisites',
            field=models.JSONField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
    ]
