# Generated by Django 6.0.1 on 2026-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admin_last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
