# Generated by Django 6.0.1 on 2026-01-18 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_chat_admin_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='exchange.chat', verbose_name='Чат'),
        ),
    ]
