# Generated by Django 6.0.1 on 2026-01-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_order_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_base', to='exchange.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_quote', to='exchange.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['base', 'quote'], name='exchange_ra_base_id_1b4c3c_idx'), models.Index(fields=['updated_at'], name='exchange_ra_updated_f2ca8c_idx')],
                'unique_together': {('base', 'quote')},
            },
        ),
    ]
