# Generated by Django 6.0.1 on 2026-01-22 05:54

import exchange.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_ratecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_card_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(db_index=True, default=exchange.models.generate_public_id, max_length=32, unique=True),
        ),
    ]
