# Generated by Django 6.0.1 on 2026-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_order_recipient_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecache',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=32, null=True),
        ),
    ]
