# Generated by Django 6.0.1 on 2026-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hex код для фона картинки'),
        ),
    ]
