# Generated by Django 6.0.1 on 2026-01-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_currency_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Проверенные реквизиты'),
        ),
    ]
