# Generated by Django 6.0.1 on 2026-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_order_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название для api (BTC к примеру)'),
        ),
    ]
