# Generated by Django 6.0.1 on 2026-02-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_alter_currency_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'description')},
        ),
    ]
