# Generated by Django 6.0.1 on 2026-02-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_alter_currency_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-pk'], 'verbose_name': 'Монета', 'verbose_name_plural': 'Монеты'},
        ),
    ]
